// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Cg9axcKeGriAB_lqanROIXKA74q4Ims',
    appId: '1:341796724832:web:2219910037c83af7e96305',
    messagingSenderId: '341796724832',
    projectId: 'todo-list-8e089',
    authDomain: 'todo-list-8e089.firebaseapp.com',
    storageBucket: 'todo-list-8e089.firebasestorage.app',
    measurementId: 'G-30B6PWQYTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCex6yVdybQcmL49xjZk0YL5xXoGxJYBFg',
    appId: '1:341796724832:android:7a13c65a4b52e1d3e96305',
    messagingSenderId: '341796724832',
    projectId: 'todo-list-8e089',
    storageBucket: 'todo-list-8e089.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3TE0Rf-9w_T5HGKg1C-Q6gTRWhDa1yLM',
    appId: '1:341796724832:ios:8461b21f93bea653e96305',
    messagingSenderId: '341796724832',
    projectId: 'todo-list-8e089',
    storageBucket: 'todo-list-8e089.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3TE0Rf-9w_T5HGKg1C-Q6gTRWhDa1yLM',
    appId: '1:341796724832:ios:8461b21f93bea653e96305',
    messagingSenderId: '341796724832',
    projectId: 'todo-list-8e089',
    storageBucket: 'todo-list-8e089.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Cg9axcKeGriAB_lqanROIXKA74q4Ims',
    appId: '1:341796724832:web:59308791cd04c4ade96305',
    messagingSenderId: '341796724832',
    projectId: 'todo-list-8e089',
    authDomain: 'todo-list-8e089.firebaseapp.com',
    storageBucket: 'todo-list-8e089.firebasestorage.app',
    measurementId: 'G-FNH7XQ8G9H',
  );
}
